// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function CheckAdmin():Promise<boolean>;

export function CloseInstaller():Promise<void>;

export function GetDefaultPath():Promise<string>;

export function LaunchApp():Promise<void>;

export function StartInstallation(arg1:backend.InstallOptions):Promise<void>;
