// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAdmin() {
  return window['go']['backend']['Installer']['CheckAdmin']();
}

export function CloseInstaller() {
  return window['go']['backend']['Installer']['CloseInstaller']();
}

export function GetDefaultPath() {
  return window['go']['backend']['Installer']['GetDefaultPath']();
}

export function LaunchApp() {
  return window['go']['backend']['Installer']['LaunchApp']();
}

export function StartInstallation(arg1) {
  return window['go']['backend']['Installer']['StartInstallation'](arg1);
}
